### ISSUE TITLE
Rephrase how double-track is described

### ISSUE THREAD

**Issue by garykac** [garykac/shinjuku#58]
From the player's perspective, it feels good to play a card and do a thing.

Try to rephrase the rule in that way.

**Comment by snekse** [comment]
From a rules perspective, if I'm laying down 2 linked tracks in a turn, I don't really need a card for the first track I laid down, I really just need a card for any station one of the tracks connects to.  It's just an order of operations error on the user's part if they don't have the right card to lay down the 2nd track. 

So if I have card C and I lay a track down to connect A<->B, I now cannot lay down a track to connect B<->C according to how the rules are written. 

But in reality, the player just messed up their logic a bit; they needed to lay down the B<->C track first, play the C card, then lay down the B<->A track. 

So the rule could be simplified to say lay down 2 connecting tracks and discard a card for one of the stations involved.

**Comment by garykac** [comment]
I was originally trying to have the rule: (a) do something, and then optionally (b) expand it a bit.

But it does appear to be confusing when phrased like that. I don't mind the "puzzle" of figuring out that you can play from C first for double-track in the A-B-C case, but it's more important that the rule be clear and easy to understand. Sadly, the current phrasing is not quite clear/easy.

 > So the rule could be simplified to say lay down 2 connecting tracks and discard a card for one of the stations involved.

I really like phrasing it like this.

Something like: "Expand: Build 1 track segment (no cost). Or build 2 connected track segments if you pay a card that matches one of the stations"

Thanks for the comment and suggestion.

**Comment by snekse** [comment]
I like it. It takes part of the puzzling away, but I think it helps new players learn the game faster.

Probably need a special call out for how Shinjuku/Yoyogi work when considering cards viable for connecting to one of those locations.

Like if I connect Nakano to Minato through Shinjuku station, which cards are viable for me to play? All 4 wards it goes through?  This is the scenario that actually brought up this topic in my head. This was where the puzzle factor came in.

**Comment by garykac** [comment]
For double-track through Shinjuku/Yoyogi, any of the 4 stations could be matched. I call this out in the rules (on page 5), but the text will need to be update with the new phrasing (since it still uses the "solve a puzzle" approach).

**Comment by garykac** [comment]
Fixed in rules v2 r10
